// Temporarily
export const images = {
  '/productos/alfs-maicena.jpg': require('../assets/productos/alfs-maicena.jpg'),
  '/productos/brownie.jpg': require('../assets/productos/brownie.jpg'),
  '/productos/carrot.jpg': require('../assets/productos/carrot.jpg'),
  '/productos/cheescakeFrutilla.jpg': require('../assets/productos/cheescakeFrutilla.jpg'),
  '/productos/chipa.jpg': require('../assets/productos/chipa.jpg'),
  '/productos/chocotorta.jpg': require('../assets/productos/chocotorta.jpg'),
  '/productos/cookieAvenaYNuez.jpg': require('../assets/productos/cookieAvenaYNuez.jpg'),
  '/productos/cupcake.jpg': require('../assets/productos/cupcake.jpg'),
  '/productos/insertImg.jpg': require('../assets/productos/insertImg.jpg'),
  '/productos/lemon.jpg': require('../assets/productos/lemon.jpg'),
  '/productos/limepie.jpg': require('../assets/productos/limepie.jpg'),
  '/productos/maicena.jpg': require('../assets/productos/maicena.jpg'),
  '/productos/panesSaborizados.jpg': require('../assets/productos/panesSaborizados.jpg'),
  '/productos/pielemon.jpg': require('../assets/productos/pielemon.jpg'),
  '/productos/pops.jpg': require('../assets/productos/pops.jpg'),
  '/productos/rogel.jpg': require('../assets/productos/rogel.jpg'),
  '/productos/sconesqueso.jpg': require('../assets/productos/sconesqueso.jpg'),
  '/productos/selva.jpg': require('../assets/productos/selva.jpg'),
  '/productos/sin resultados.jpg': require('../assets/productos/sin resultados.jpg'),
  '/productos/tartaAlmendra.jpg': require('../assets/productos/tartaAlmendra.jpg'),
  '/productos/tartaFrutal.jpg': require('../assets/productos/tartaFrutal.jpg'),
  '/productos/tiramisu.jpg': require('../assets/productos/tiramisu.jpg'),
  '/productos/tortaOreo.jpg': require('../assets/productos/tortaOreo.jpg'),
  '/productos/tresleches.jpg': require('../assets/productos/tresleches.jpg'),
};
